name: pingpong

services:
  app-server:
    build: ./app-server
    container_name: app-server
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - back-tier
    restart: on-failure
    volumes:
      - static-files:/usr/src/app/static-files
      - media-files:/usr/src/app/media-files

  database:
    build: ./database
    container_name: database
    env_file:
      - ./.env
    networks:
      - back-tier
    shm_size: 128mb
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data

  web-server:
    build: ./web-server
    container_name: web-server
    depends_on:
      - app
      - db
    networks:
      - back-tier
    ports:
      - '80:80'
    restart: on-failure
    volumes:
      - static-files:/usr/share/nginx/html/static
      - media-files:/usr/share/nginx/html/media

#  portainer:
#    image: portainer/portainer-ce:latest
#    container_name: portainer
#    networks:
#      - intra
#    ports:
#      - '9443:9443'
#    restart: on-failure
#    volumes:
#      - portainer-data:/data
#      - /var/run/docker.sock:/var/run/docker.sock


networks:
  back-tier: {}


volumes:
  db-data: {}
  static-files: {}
  media-files: {}
