name: pingpong

services:
  backend:
    build: ./apps/backend
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - back-tier
    restart: on-failure
    volumes:
      - static-files:/usr/src/app/static-files
      - media-files:/usr/src/app/media-files

  postgres:
    build: ./apps/postgres
    container_name: postgres
    env_file:
      - ./.env
    networks:
      - back-tier
    shm_size: 128mb
    restart: on-failure
    volumes:
      - db:/var/lib/postgresql/data

  nginx:
    build: ./apps/nginx
    container_name: nginx
    depends_on:
      - backend
      - postgres
    networks:
      - back-tier
    ports:
      - '80:80'
    restart: on-failure
    volumes:
      - static:/usr/share/nginx/html/static
      - media:/usr/share/nginx/html/media

#  portainer:
#    image: portainer/portainer-ce:latest
#    container_name: portainer
#    networks:
#      - intra
#    ports:
#      - '9443:9443'
#    restart: on-failure
#    volumes:
#      - portainer-data:/data
#      - /var/run/docker.sock:/var/run/docker.sock


networks:
  back-tier: {}


volumes:
  db: {}
  static: {}
  media: {}
